parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://jeyser:jeyser@database:3306/jeyser'

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: UTF8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
              auto_mapping: true
              dql:
                  datetime_functions:
                      day: App\DQL\Day
                      year: App\DQL\Year
                      month: App\DQL\Month
              mappings:
                  App:
                      is_bundle: false
                      type: annotation
                      dir: '%kernel.project_dir%/src/Entity'
                      prefix: 'App\Entity'
                      alias: App
