easy_admin:
    entities:
        Avenant:
          class: App\Entity\Project\Av
          list :
              fields:
                - 'id'
                - 'etude'
                - 'objet'
        ContactClient:
            class: App\Entity\Project\ClientContact
        Competence:
            class: App\Entity\Hr\Competence
        Document:
            class: App\Entity\Publish\Document
        Employe:
            class: App\Entity\Personne\Employe
        Etude:
            class: App\Entity\Project\Etude
            list :
                fields:
                  - 'id'
                  - 'Nom'
                  - 'Mandat'
                  - 'dateCreation'
                  - 'dateModification'
                  - 'stateDescription'
                  - 'confidentiel'
        Filiere:
            class: App\Entity\Personne\Filiere
        Mandat:
            class: App\Entity\Personne\Mandat
        Membre:
            class: App\Entity\Personne\Membre
        Mission:
            class: App\Entity\Project\Mission
            list :
              fields:
                - 'id'
                - 'etude'
                - 'intervenant'
                - 'debutOm'
                - 'finOm'
                - 'pourcentageJunior'
        Personne:
            class: App\Entity\Personne\Personne
        Poste:
            class: App\Entity\Personne\Poste
        Prospect:
            class: App\Entity\Personne\Prospect
        RelatedDocument:
            class: App\Entity\Publish\RelatedDocument
        Suivi:
            class: App\Entity\Project\Suivi
        User:
            class: App\Entity\User\User
