# app/config/admin.yml
### Espace admin
easy_admin:
    entities:
        Avenant:
          class: Mgate\SuiviBundle\Entity\Av
          list :
              fields:
                - 'id'
                - 'etude'
                - 'objet'
        ContactClient:
            class: Mgate\SuiviBundle\Entity\ClientContact
        Competence:
            class: N7consulting\RhBundle\Entity\Competence
        Document:
            class: Mgate\PubliBundle\Entity\Document
        Employe:
            class: Mgate\PersonneBundle\Entity\Employe
        Etude:
            class: Mgate\SuiviBundle\Entity\Etude
            list :
                fields:
                  - 'id'
                  - 'Nom'
                  - 'Mandat'
                  - 'dateCreation'
                  - 'dateModification'
                  - 'stateDescription'
                  - 'confidentiel'
        Filiere:
            class: Mgate\PersonneBundle\Entity\Filiere
        Mandat:
            class: Mgate\PersonneBundle\Entity\Mandat
        Membre:
            class: Mgate\PersonneBundle\Entity\Membre
        Mission:
            class: Mgate\SuiviBundle\Entity\Mission
            list :
              fields:
                - 'id'
                - 'etude'
                - 'intervenant'
                - 'debutOm'
                - 'finOm'
                - 'pourcentageJunior'
        Personne:
            class: Mgate\PersonneBundle\Entity\Personne
        Poste:
            class: Mgate\PersonneBundle\Entity\Poste
        Prospect:
            class: Mgate\PersonneBundle\Entity\Prospect
        RelatedDocument:
            class: Mgate\PubliBundle\Entity\RelatedDocument
        Suivi:
            class: Mgate\SuiviBundle\Entity\Suivi
        User:
            class: Mgate\UserBundle\Entity\User
